//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TidyCSharp.Cli.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TidyCSharp.Cli.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrivateModifierRemover: The file path is either null or the file does not exist.
        /// </summary>
        internal static string PrivateModifierCleanUpFailed {
            get {
                return ResourceManager.GetString("PrivateModifierCleanUpFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning - C# Code Cleanup.
        /// </summary>
        internal static string WarningCaptionCleanup {
            get {
                return ResourceManager.GetString("WarningCaptionCleanup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning - Organize using directives.
        /// </summary>
        internal static string WarningCaptionOrganizeUsing {
            get {
                return ResourceManager.GetString("WarningCaptionOrganizeUsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is strongly recommended that you close all open windows before starting this process..
        /// </summary>
        internal static string WarnOnCodeCleanUp {
            get {
                return ResourceManager.GetString("WarnOnCodeCleanUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is strongly recommended that you close all open windows before starting this process..
        /// </summary>
        internal static string WarnOnOrganizeUsings {
            get {
                return ResourceManager.GetString("WarnOnOrganizeUsings", resourceCulture);
            }
        }
    }
}
